export const styles = {
  wrapper: { fontFamily: "'Sentient', Georgia, serif", maxWidth: 780, margin: "0 auto", padding: "20px 12px", color: "#1a2e35" },
  card: { background: "#fff", borderRadius: 14, border: "1px solid #e4eaec", boxShadow: "0 2px 12px rgba(0,0,0,0.04)" },
  fieldHalf: { flex: "1 1 calc(50% - 8px)", minWidth: 200, display: "flex", flexDirection: "column" },
  fieldFull: { flex: "1 1 100%", display: "flex", flexDirection: "column" },
  label: { fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em", color: "#3d5a5e", marginBottom: 6 },
  input: { padding: "11px 12px", border: "1.5px solid #d1dde0", borderRadius: 8, fontSize: 14, color: "#1a2e35", background: "#fff", boxSizing: "border-box", width: "100%", transition: "border 0.2s, box-shadow 0.2s" },
  inputError: { borderColor: "#e05252" },
  select: { padding: "11px 12px", border: "1.5px solid #d1dde0", borderRadius: 8, fontSize: 14, background: "#fff", cursor: "pointer", boxSizing: "border-box", width: "100%" },
  textarea: { padding: "11px 12px", border: "1.5px solid #d1dde0", borderRadius: 8, fontSize: 14, color: "#1a2e35", resize: "vertical", fontFamily: "inherit", background: "#fff", boxSizing: "border-box", width: "100%" },
  errorText: { fontSize: 11, color: "#e05252", marginTop: 4 },
  btnPrimary: { padding: "12px 28px", background: "#0B5D5F", color: "#fff", border: "none", borderRadius: 8, fontSize: 14, fontFamily: "'FT Calhern', sans-serif", fontWeight: 600, cursor: "pointer", letterSpacing: "0.01em", transition: "background 0.2s" },
  stepDot: { width: 28, height: 28, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, border: "2px solid #d1dde0", color: "#94a3b8", background: "#fff", transition: "background 0.2s, color 0.2s, border-color 0.2s" },
  stepDotActive: { borderColor: "#0B5D5F", background: "#0B5D5F", color: "#fff" },
  chip: { padding: "6px 14px", background: "#f0f5f5", borderRadius: 20, fontSize: 13, fontWeight: 500, color: "#0B5D5F", border: "1px solid #d6e5e5" },
  calendarCell: { aspectRatio: "1", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, borderRadius: "50%" },
  calendarCellButton: { aspectRatio: "1", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, borderRadius: "50%", border: "2px solid transparent", background: "none", padding: 0 },
  navButton: { background: "none", border: "1.5px solid #d1dde0", borderRadius: 8, width: 34, height: 34, fontSize: 18, cursor: "pointer", color: "#0B5D5F", display: "flex", alignItems: "center", justifyContent: "center", lineHeight: 1 },
  successIcon: { width: 56, height: 56, borderRadius: "50%", background: "#0B5D5F", color: "#fff", fontSize: 28, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px" },
  debugBox: { marginTop: 20, padding: 16, background: "#eef4f5", borderRadius: 8, border: "1px solid #d1dde0", maxWidth: 480, marginLeft: "auto", marginRight: "auto" },
  timezoneBanner: { fontSize: 13, color: "#3d5a5e", background: "#f0f7f7", border: "1px solid #d6e5e5", borderRadius: 8, padding: "10px 14px", marginBottom: 24 },
};
